FROM golang:1.24 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod tidy && go mod verify
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o grep-server ./cmd/server/main.go

FROM alpine:3.21

WORKDIR /app
RUN adduser -D -g '' appuser
COPY --from=builder /app/grep-server .
RUN chown -R appuser:appuser /app
USER appuser

CMD ["./grep-server", "--port", "50051"]