// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/grep_service/grep.proto

package grepsvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrepService_ProcessChunk_FullMethodName = "/grepsvc.GrepService/ProcessChunk"
	GrepService_HealthCheck_FullMethodName  = "/grepsvc.GrepService/HealthCheck"
)

// GrepServiceClient is the client API for GrepService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrepServiceClient interface {
	ProcessChunk(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*ChunkResponse, error)
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type grepServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrepServiceClient(cc grpc.ClientConnInterface) GrepServiceClient {
	return &grepServiceClient{cc}
}

func (c *grepServiceClient) ProcessChunk(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*ChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkResponse)
	err := c.cc.Invoke(ctx, GrepService_ProcessChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grepServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, GrepService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrepServiceServer is the server API for GrepService service.
// All implementations must embed UnimplementedGrepServiceServer
// for forward compatibility.
type GrepServiceServer interface {
	ProcessChunk(context.Context, *ChunkRequest) (*ChunkResponse, error)
	HealthCheck(context.Context, *emptypb.Empty) (*HealthResponse, error)
	mustEmbedUnimplementedGrepServiceServer()
}

// UnimplementedGrepServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrepServiceServer struct{}

func (UnimplementedGrepServiceServer) ProcessChunk(context.Context, *ChunkRequest) (*ChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessChunk not implemented")
}
func (UnimplementedGrepServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGrepServiceServer) mustEmbedUnimplementedGrepServiceServer() {}
func (UnimplementedGrepServiceServer) testEmbeddedByValue()                     {}

// UnsafeGrepServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrepServiceServer will
// result in compilation errors.
type UnsafeGrepServiceServer interface {
	mustEmbedUnimplementedGrepServiceServer()
}

func RegisterGrepServiceServer(s grpc.ServiceRegistrar, srv GrepServiceServer) {
	// If the following call pancis, it indicates UnimplementedGrepServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrepService_ServiceDesc, srv)
}

func _GrepService_ProcessChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrepServiceServer).ProcessChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrepService_ProcessChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrepServiceServer).ProcessChunk(ctx, req.(*ChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrepService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrepServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrepService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrepServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GrepService_ServiceDesc is the grpc.ServiceDesc for GrepService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrepService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grepsvc.GrepService",
	HandlerType: (*GrepServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessChunk",
			Handler:    _GrepService_ProcessChunk_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GrepService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grep_service/grep.proto",
}
